# Generated by Django 4.1.1 on 2022-09-08 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0002_alter_commentitem_email_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentitem',
            name='email_name',
            field=models.EmailField(max_length=50, validators=[django.core.validators.EmailValidator(message='Введите конкретный email')], verbose_name='Электронная почта автора:'),
        ),
    ]
