# Generated by Django 4.1.1 on 2022-09-08 19:19

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0003_alter_commentitem_email_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentitem',
            name='email_name',
            field=models.EmailField(max_length=50, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid'), django.core.validators.RegexValidator(re.compile('^[-\\w]+\\Z'), 'Enter a valid “slug” consisting of Unicode letters, numbers, underscores, or hyphens.', 'invalid'), django.core.validators.EmailValidator(message='Введите конкретный email')], verbose_name='Электронная почта автора:'),
        ),
    ]
