# Generated by Django 4.1.1 on 2022-09-09 12:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0006_alter_caritem_name_alter_countryitem_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentitem',
            name='email_name',
            field=models.EmailField(max_length=50, validators=[django.core.validators.EmailValidator(message='Введите конкретный email')], verbose_name='Электронная почта автора:'),
        ),
    ]
