# Generated by Django 4.1.1 on 2022-09-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0007_alter_commentitem_email_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentitem',
            name='comment',
            field=models.CharField(max_length=250, verbose_name='Комментарий от <django.db.models.fields.EmailField>:'),
        ),
    ]
