# Generated by Django 3.2.15 on 2022-09-10 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0011_rename_name_produceritem_name_p'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countryitem',
            old_name='name',
            new_name='country',
        ),
    ]
