# Generated by Django 3.2.15 on 2022-09-10 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0012_rename_name_countryitem_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produceritem',
            old_name='name_p',
            new_name='producer',
        ),
    ]
