# Generated by Django 3.2.15 on 2022-09-11 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0013_rename_name_p_produceritem_producer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caritem',
            old_name='name',
            new_name='name_car',
        ),
        migrations.RenameField(
            model_name='caritem',
            old_name='producer',
            new_name='name_producer',
        ),
        migrations.RenameField(
            model_name='commentitem',
            old_name='car',
            new_name='name_car',
        ),
        migrations.RenameField(
            model_name='countryitem',
            old_name='country',
            new_name='name_country',
        ),
        migrations.RenameField(
            model_name='produceritem',
            old_name='country',
            new_name='name_country',
        ),
        migrations.RenameField(
            model_name='produceritem',
            old_name='producer',
            new_name='name_producer',
        ),
    ]
